spring:
  application:
    name: demo
  security:
    oauth2:
      client:
        registration:
          foo:
            client-id: foo
            client-secret: ib89MiRdiwSiiT4MCifG1pDafgvOLYrA
            scope:
              - openid
              - profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          bar:
            client-id: bar
            client-secret: opBmYtYgiL1GKUMc9cPlV6pYwwpI9Ced
            scope:
              - openid
              - profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          foo:
            issuer-uri: http://localhost:9000/realms/sample
          bar:
            issuer-uri: http://localhost:9000/realms/sample